sudo: required
services:
  - docker

before_install:
  - docker build -t backtest .

script:
  - true

after_success:
  - docker build -t belalelhossany/back .
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push belalelhossany/back
deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: MarioPlexBack
  env: Marioplexback-env
  bucket_name: elasticbeanstalk-us-east-1-340227665405
  bucket_path: MarioPlexBack
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
