dist: bionic
sudo: false
language: node_js
install: 
 - git clone https://github.com/MohmedMonsef/Marioplex-Backend
 - haha
script:
  - true
notifications:
  email:
    recipients:
      - belalelhossany12@gmail.com
before_deploy: 
  - openssl aes-256-cbc -K $encrypted_795c2fa3db91_key -iv $encrypted_795c2fa3db91_iv
     -in key.pem.enc -out /opt/key/key.pem -d
deploy:
 - bash Deploy.sh
