dist: bionic
sudo: false
language: node_js
install: 
 - git clone https://github.com/MohmedMonsef/Marioplex-Backend
script:
  - true
notifications:
  email:
    recipients:
      - belalelhossany12@gmail.com
before_deploy: 
- eval "$(ssh-agent -s)"
- chmod 600 key.pem
- ssh-add key.pem
deploy:
 - bash Deploy.sh
