sudo: required
services:
  - docker 
script:
  - true
  - echo " SCRIPT FINISHED " 
after_success:
  - docker build -t belalelhossany/backend .
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push belalelhossany/backend
deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-west-1
  app: BackEnd
  env: Backend-env
  bucket_name: marioplex
  bucket_path: Back
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
