dist: bionic
sudo: false
language: node_js
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- git clone https://github.com/BelalElhossany/devOps
- cd devOps
- eval "$(ssh-agent -s)"
- chmod 600 haha.pem
- ssh-add haha.pem
- ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i haha.pem ubuntu@ec2-52-205-254-29.compute-1.amazonaws.com
- git clone https://github.com/MohmedMonsef/Marioplex-Backend
install: 
  script:
    - true
notifications:
  email:
    recipients:
      - belalelhossany12@gmail.com
deploy:
 provider: script
 skip_cleanup: true
 script: bash Deploy.sh 
