dist: bionic
sudo: false
language: node_js
install: 
 - git clone https://github.com/MohmedMonsef/Marioplex-Backend
script:
  - true
notifications:
  email:
    recipients:
      - belalelhossany12@gmail.com
deploy:
 - bash Deploy.sh
